- hosts: all
  become: true
  vars:
    kubeconfig: "~/.kube/config"
  tasks: 
    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml --kubeconfig={{ kubeconfig }}
    - name: delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml --kubeconfig={{ kubeconfig }}
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yml --kubeconfig={{ kubeconfig }}
    - name: create new service
      command: kubectl apply -f /home/ubuntu/Service.yml --kubeconfig={{ kubeconfig }}

