kind: Deployment
apiVersion: apps/v1
metadata:
   name: ardaucardeployment
spec:
   replicas: 2
   selector:      
    matchLabels:
     app: ardaucar
   template:
      metadata:
        labels:
          app: ardaucar
      spec:
       containers:
        - name: ardaucar
          image: ardaeu/pipeline1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
